app/urls.py
from django.urls import path, re_path
from app import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [

    # The home page
    
    path('', views.index, name='home'),

    #Vezetői view-k
    path('gyerek/', views.GyerekCreate, name="gyerek"),
    path('gyerek/<str:pk>/', views.GyerekUpdate, name="gyerek_mod"),
    path('gyerek_lista/', views.GyerekList, name="gyerek_lista"),
    path('gyerek_lista_export/', views.GyerekListExport, name="gyerek_lista_export"),
    

    path('szulo/', views.SzuloCreate, name="szulo"),
    path('szulo/<str:pk>/', views.SzuloUpdate, name="szulo_mod"),
    path('szulo_lista/', views.SzuloList, name="szulo_lista"),
    
    path('szulo_lista_export/', views.SzuloListExport, name="szulo_lista_export"),
   
    path('guru/', views.GuruCreate, name="guru"),
    path('guru/<str:pk>/', views.GuruUpdate, name="guru_mod"),
    path('guru_lista/', views.GuruList, name="guru_lista"),

    path('foglalkozas_tipus/', views.Foglalkozas_tipusCreate, name="foglalkozas_tipus"),
    path('foglalkozas_tipus/<str:pk>/', views.Foglalkozas_tipusUpdate, name="foglalkozas_tipus_mod"),
    path('foglalkozas_tipus_lista/', views.Foglalkozas_tipusList, name="foglalkozas_tipus_lista"),
    
    path('helyszin/', views.HelyszinView, name="helyszin"),
    path('helyszin/<str:pk>/', views.HelyszinUpdate, name="helyszin_mod"),
    path('helyszin_lista/', views.HelyszinList, name="helyszin_lista"),

    path('terapia/', views.CsoportCreate, name="terapia"),
    path('terapia/<str:pk>/',  views.CsoportUpdate, name='terapia_mod'),
    path('terapia_lista/', views.CsoportList, name="terapia_lista"),
    path('terapia_lista_export/', views.CsoportListExport, name="terapia_lista_export"),

    path('ora/', views.OraCreate, name="ora"),
    path('ismetles/<str:pk>/', views.OraIsmetles, name="ismetles"),
    path('ora_lista/', views.OraListEgy, name="ora_lista"),
    path('ora_lista_meg/', views.OraListEgyMeg, name="ora_lista_meg"),
    path('nemmegtartott_havi_ora_lista/', views.OraListEgyNem, name="nemmegtartott_havi_ora_lista"),

    path('ora_lista_harom/', views.OraListHarom, name="ora_lista_harom"),
    path('ora_lista_full/', views.OraListFull, name="ora_lista_full"),
    path('ora/<str:pk>/', views.OraUpdate, name="ora_mod"),
    path('ora_torles/<str:pk>/', views.OraTorles, name="ora_torles"),
 

    path('egyedi/', views.EgyediCreate, name="egyedi"),
    path('egyedi_lista/', views.EgyediList, name="egyedi_lista"),
    path('egyedi/<str:pk>/', views.EgyediUpdate, name="egyedi_mod"),
    path('egyedi_torles/<str:pk>/', views.EgyediTorles, name="egyedi_torles"),

    path('napiuzi/', views.NapiuziCreate, name="napiuzi"),
    path('napiuzi_lista/', views.NapiuziList, name="napiuzi_lista"),
    path('napiuzi/<str:pk>/', views.NapiuziUpdate, name="napiuzi_mod"),
    path('napiuzi_torles/<str:pk>/', views.NapiuziTorles, name="napiuzi_torles"),
    
    path('jelenleti/<str:pk>/', views.JelenletiView, name="jelenleti"),
    path('jelenleti_regen/<str:pk>/', views.Jelenleti_regenerate_View, name="jelenleti_regen"),
    
    path('befizetes/', views.BefizetesView, name="befizetes"),
    path('befizetes_lista/', views.BefizetesList, name="befizetes_lista"),
    path('befizetes/<str:pk>/', views.BefizetesUpdate, name="befizetes_mod"),

    path('egyenlegek/', views.EgyenlegekView, name="egyenlegek"),
    path('attekinto/', views.AttekintoView, name="attekinto"),
    path('osszesitett_elszamolas/', views.Osszesített_elszamolas, name="osszesitett_elszamolas"),
    path('export_havi_osszesites/<str:pk>/', views.export_havi_osszesites, name="export_havi_osszesites"),
    path('export_havi_osszesites_honap/<str:pk>/', views.export_havi_osszesites_honap, name="export_havi_osszesites_honap"),
    path('osszesito/', views.osszesito, name="osszesito"),
    

    path('uj_felhasznalo/', views.register_user, name="uj_felhasznalo"),
    path('felhasznalok/', views.felhasznalok, name="felhasznalok"),
    path('user_mod/<str:pk>/', views.user_mod, name="user_mod"),
    path('jelszocsere/', views.jelszocsere, name="jelszocsere"),
    path('passwchange/<str:pk>/', views.passwchange, name="passwchange"),

    

    path('naptar/', views.naptar, name="naptar"),

    path('guru_lap/', views.guru_lap, name='guru_lap'),
    

    #re_path(r'^.*\.*', views.pages, name='pages'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emu/urls.py
#emu URL Configuration

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django.conf.urls import url
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
import datetime
from django.urls import reverse
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User



# Családi adatok
class Szulo(models.Model):
    #user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    nev = models.CharField('* Szülő neve', max_length=50, null=True, blank=False)
    telefon = models.CharField('* Telefonszáma', max_length=16, null=True, blank=False)
    email = models.EmailField('* E-mail cím', null=True, blank=False)
    lev_cim = models.CharField('* Számlázási cím', max_length=80, null=True, blank=False)
    szerzodo = models.BooleanField('Szerződő fél', default=False)
    aktiv = models.BooleanField('Aktív', default=True)
    rogzitve = models.DateTimeField('Rögzítve', auto_now_add=True)
    modositva = models.DateTimeField('Módosítva', auto_now=True)
    
    #rogzito = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nev
    def gyerekek(self):        
        return Csalad.objects.filter(szulo=self.id)
    
    class Meta:
        ordering = ['nev']
        unique_together = ['nev', 'telefon']

class Gyerek(models.Model):
    nev = models.CharField('* Gyerek neve', max_length=50, blank=False, null=True)
    szul_ido = models.DateField('* Gyerek születési ideje', auto_now_add=False, auto_now=False, null=True)
    kod = models.CharField('Gyerek kód', max_length=50, blank=False, null=True)
    anyja_neve = models.CharField('* Anyja születési neve', max_length=50, blank=False, null=True)
    aktiv = models.BooleanField('Oktatásban van', default=True)
    #rogzitve = models.DateTimeField('Rögzítve', auto_now_add=True)
    #rogzito = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def age(self):
        return timezone.now().year - self.szul_ido.year
        
    def __str__(self):
        return self.kod

    def szulok(self):        
        return Csalad.objects.filter(gyerek=self.id)

    def csoportok(self):
        return GyerektoCsoport.objects.filter(gyerek=self.id)

        

    class Meta:
        ordering = ['kod']
        unique_together = ['nev', 'szul_ido', 'anyja_neve']

class Csalad(models.Model):
    szulo = models.ForeignKey(Szulo, on_delete=models.CASCADE, verbose_name='Szülő', blank=False)
    gyerek = models.ForeignKey(Gyerek, on_delete=models.CASCADE, verbose_name='Gyerek', blank=False)  
    def __str__(self):
        elnevezes = self.szulo.nev + ' - ' + self.gyerek.nev
        return elnevezes
    class Meta:
        unique_together = ['gyerek', 'szulo']

class Helyszin(models.Model):
    elnevezes = models.CharField('* Foglalkozások helyszín elnevezése', max_length=30, blank=False, null=True, unique=True)
    varos = models.CharField('* Város', max_length=30, blank=False, null=True, unique=True)
    cim = models.CharField('* Címe', max_length=50, blank=False, null=True, unique=True)

    def __str__(self):
        return self.elnevezes

    class Meta:
        ordering = ['elnevezes']
    


# Guru - Foglalkozások - Tanítvány adatok
class Guru(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE, verbose_name='* Felhasználó')
    nev = models.CharField('* Név', max_length=50, blank=False, null=True, unique=True)
    kepzettseg = models.CharField('* Képzettség', max_length=100, blank=False, null=True )
    bemutatkozas = RichTextField('* Bemutatkozás',null=True, blank=True)
    fenykep = models.ImageField('Fénykép', default="guru.jpg", null=True, blank=True)
    helyszin = models.ForeignKey(Helyszin, on_delete=models.CASCADE, null=True, verbose_name='* Helyszín')
    email = models.EmailField('* E-mail cím', null=True, blank=False)
    aktiv = models.BooleanField('Aktív', default=True)

    def __str__(self):
        return self.nev

class Foglalkozas_tipus(models.Model):
    KATEGORIAK = (
            ('Egyéni', 'Egyéni'),
			('Páros', 'Páros'),
			('Csoportos', 'Csoportos'),
            ('Család terápia', 'Család terápia'),
            ('Szülői', 'Szülői'),
            ('Egyéb', 'Egyéb'),
			)

    nev = models.CharField('* Foglalkozás típus elnevezése ', max_length=50, blank=False, null=True, unique=True)
    ar = models.IntegerField('* Foglalkozás típus ára Ft-ban', blank=False, null=True)
    cat = models.CharField('* Foglalkozás típus kategória ', max_length=30, blank=False, null=True, choices=KATEGORIAK)
    
    #rogzitve = models.DateTimeField('Rögzítve', auto_now_add=True)
    #rogzito = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nev
    class Meta:
        ordering = ['cat']


class Csoport(models.Model):#A terápia modelje. Csak a felületek vannak átnevezve
    nev = models.CharField('* Terápia elnevezése ', max_length=50, blank=False, null=True, unique=True)
    foglalkozas_tipus = models.ForeignKey(Foglalkozas_tipus, on_delete=models.CASCADE, verbose_name='* Típus')
    helyszin = models.ForeignKey(Helyszin, on_delete=models.CASCADE, null=True, verbose_name='* Helyszín')
    aktiv = models.BooleanField('Aktív', default=True)

    #rogzitve = models.DateTimeField('Rögzítve', auto_now_add=True)
    #rogzito = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nev

    def guruk(self):        
        return GurutoCsoport.objects.filter(csoport=self.id)
    def gyerekek(self):        
        return GyerektoCsoport.objects.filter(csoport=self.id)
    
    class Meta:
        ordering = ['nev']
        


class GurutoCsoport(models.Model):
    guru = models.ForeignKey(Guru, on_delete=models.CASCADE, verbose_name='Terapeuta')
    csoport = models.ForeignKey(Csoport, on_delete=models.CASCADE, verbose_name='Terápia')
    def __str__(self):
        elnevezes = self.csoport.nev + ' - ' + self.guru.nev
        return elnevezes   
    class Meta:
        unique_together = ['csoport', 'guru']
        ordering = ['csoport']


class GyerektoCsoport(models.Model):
    gyerek = models.ForeignKey(Gyerek, on_delete=models.CASCADE, verbose_name='Gyerek')
    csoport = models.ForeignKey(Csoport, on_delete=models.CASCADE, verbose_name='Terápia')
    def __str__(self):
        elnevezes = self.csoport.nev + ' - ' + self.gyerek.nev
        return elnevezes   
    class Meta:
        unique_together = ['csoport', 'gyerek']
        ordering = ['csoport']


class Ora(models.Model):
    kezdes = models.DateTimeField('* Kezdés')
    befejezes = models.DateTimeField('* Befejezés')
    csoport = models.ForeignKey(Csoport, on_delete=models.CASCADE, verbose_name='* Terápia')
    feljegyzes = models.TextField(null=True, blank=True)
    megtartott = models.BooleanField('Megtartott', default=False)
    lezart = models.BooleanField('Lezárva', default=False)
    #rogzitve = models.DateTimeField('Rögzítve', auto_now_add=True)
    #rogzito = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        elnevezes = self.csoport.nev + ' - ' + str(self.kezdes)
        return elnevezes
    
    def guruk(self):
        csoport=self.csoport        
        return GurutoCsoport.objects.filter(csoport=csoport)
    
    def gyerekek(self):
        csoport=self.csoport        
        return GyerektoCsoport.objects.filter(csoport=csoport)

    class Meta:
        unique_together = ['csoport', 'kezdes']
        ordering = ['csoport', 'kezdes']

class Jelenleti(models.Model):

    ALLAPOT = (
            (0, 'Nincs beállítva'),
			(1, 'Jelen volt'),
			(2, '100%-os lemondás'),
            (3, '0%-os lemondás'),
			)


    ora = models.ForeignKey(Ora, on_delete=models.CASCADE, verbose_name='Óra')
    gyerek = models.ForeignKey(Gyerek, on_delete=models.CASCADE, verbose_name='Gyerek')
    status = models.IntegerField(default=0, null=True, choices=ALLAPOT, verbose_name='Jelenléte')
    #rogzitve = models.DateTimeField('Rögzítve', auto_now_add=True)
    #rogzito = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        elnevezes = str(self.ora) +' - '+ self.gyerek.kod
        return elnevezes
    class Meta:
        unique_together = ['ora', 'gyerek']

class Befizetes(models.Model):
    szulo = models.ForeignKey(Szulo, on_delete=models.CASCADE, verbose_name='* Szülő')
    osszeg = models.IntegerField('* Összeg')
    datum = models.DateField(auto_now=True, null=True, auto_now_add=False)
    megjegyzes = RichTextField(null=True, blank=True, verbose_name='Megjegyzés')
    rogzitve = models.DateTimeField('Rögzítve', auto_now_add=True, blank=True)
    rogzito = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    def __str__(self):
        elnevezes = self.szulo.nev +' - '+ str(self.datum) +' - ' + str(self.osszeg)
        return elnevezes


class Egyedi(models.Model):

    TIPUS = (
            ('Alapozó szakasz', 'Alapozó szakasz'),
			('Online tréning', 'Online tréning'),
			('Felvétel', 'Felvétel'),
            )


    idopont = models.DateTimeField('Időpont')
    tipus = models.CharField('Típus', null=True, blank=True, choices=TIPUS, max_length=40)
    letszam = models.IntegerField('Léteszám', null=True)
    megtartva = models.BooleanField('Megtartva', default=False)
    leiras = models.CharField('Leiras', null=True, blank=True, max_length=60)
    ar = models.IntegerField('Ára', null=True)


    def __str__(self):
        elnevezes = self.tipus + ' - ' + str(self.idopont)
        return elnevezes

    class Meta:
        unique_together = ['idopont', 'tipus']
        ordering = ['idopont']

class Napiuzi(models.Model):
    szoveg = models.TextField('Üzenet', null=True )
    rogzitve = models.DateField('Rögzítve', auto_now_add=True)
    rogzito = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.szoveg[:30]

    class Meta:
        ordering = ['rogzitve']



            

emu/templates/create_form.html
{% extends "layouts/base.html" %}

{% block title %} {{ Form_neve }} {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini pace-primary {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- adminlte-->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

  <link rel="stylesheet" href="/static/assets/css/jquery.datetimepicker.min.css" >
  

{% endblock stylesheets %}

{% block content %}  

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ Form_neve }}</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
       
        <div class="card-body">
          
          <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            
            <hr style="width:50%;text-align:left;margin-left:0">
            A *-al jelölt mezők kitöltése kötelező!
        </div>

        <!-- /.card-body -->
        <div class="card-footer">
          <button class="btn btn-danger" type="submit">Mentés</button>
          </form>
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>


  <script src="/static/assets/plugins/jquery/jquery.datetimepicker.full.min.js"></script>

    <script>
    $(function () {
      $.datetimepicker.setLocale('hu');
      $("#id_kezdes").datetimepicker({
        format: 'Y-m-d H:i',
        
      });
      $("#id_befejezes").datetimepicker({
        format: 'Y-m-d H:i',
        
      });
      
      $("#id_idopont").datetimepicker({
        format: 'Y-m-d H:i',
        
      });


    });
  </script>

{% endblock javascripts %}

emu/templates/delete.html
{% extends "layouts/base.html" %}

{% block title %} {{ Form_neve }} {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini pace-primary {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- pace-progress -->
  <link rel="stylesheet" href="/static/assets/plugins/pace-progress/themes/black/pace-theme-flat-top.css">
  <!-- adminlte-->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

  <link rel="stylesheet" href="/static/assets/css/jquery.datetimepicker.min.css" >
  

{% endblock stylesheets %}

{% block content %}  

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ objektum }} törlése</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
       
        <div class="card-body">
          
          <p>Biztos törölni szeretné a "{{objektum}}" objektumot ?</p>

		    <form action="{% url link objektum.id  %}" method="POST">
				
				{% csrf_token %}
				

			
                  <!-- /.card-body -->
        <div class="card-footer">
          <a class="btn btn-warning" href="{% url 'home' %}">Mégse</a>
          <button class="btn bg-gradient-danger" type="submit" name="Confirm">Törlés</button>
          </form>
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- pace-progress -->
  <script src="/static/assets/plugins/pace-progress/pace.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

  <script src="/static/assets/plugins/jquery/jquery.datetimepicker.full.min.js"></script>

    <script>
    $(function () {
      $.datetimepicker.setLocale('hu');
      $("#id_kezdes").datetimepicker({
        format: 'Y-m-d H:i',
        
      });
      $("#id_befejezes").datetimepicker({
        format: 'Y-m-d H:i',
        
      });
      
      $("#id_idopont").datetimepicker({
        format: 'Y-m-d H:i',
        
      });


    });
  </script>

{% endblock javascripts %}

emu/templates/ismetles.html
{% extends "layouts/base.html" %}

{% block title %} Blank Page {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini pace-primary {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- pace-progress -->
  <link rel="stylesheet" href="/static/assets/plugins/pace-progress/themes/black/pace-theme-flat-top.css">
  <!-- adminlte-->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %}  
  <div class="content-wrapper">
  <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          {{ora.kezdes}} - {{ora.befejezes}} --- {{ora.csoport}}
        </div>
        <div class="card-body">
          <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p}}
            <button class="btn btn-danger" type="submit">Mentés</button>
            </form>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
           {% for kezd in kezdes %}
            {{kezd}}
          {% endfor %}
        </div>
        
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <script src="/static/assets/plugins/jquery/jquery.formset.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- pace-progress -->
  <script src="/static/assets/plugins/pace-progress/pace.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

emu/templates/oracreate.html
{% extends "layouts/base.html" %}

{% block title %} {{ Form_neve }} {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini pace-primary {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- pace-progress -->
  <link rel="stylesheet" href="/static/assets/plugins/pace-progress/themes/black/pace-theme-flat-top.css">
  <!-- adminlte-->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

  <link rel="stylesheet" href="/static/assets/css/jquery.datetimepicker.min.css" >
  

{% endblock stylesheets %}

{% block content %}  

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ Form_neve }}</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Adatok:</h3>

          
        </div>
        <div class="card-body">
          
          <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            {{ ismetles_form.as_p }}
            
        </div>
          <hr style="width:50%;text-align:left;margin-left:0">
            A *-al jelölt mezők kitöltése kötelező!
          <hr style="width:50%;text-align:left;margin-left:0">

        <!-- /.card-body -->
        <div class="card-footer">
          <button class="btn btn-danger" type="submit">Mentés</button> <a class="btn bg-gradient-success" href="{% url 'ora_lista' %}">Óra lista</a>
          </form>
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- pace-progress -->
  <script src="/static/assets/plugins/pace-progress/pace.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  

  <script src="/static/assets/plugins/jquery/jquery.datetimepicker.full.min.js"></script>
  
    <script>
    $(function () {
      $.datetimepicker.setLocale('hu');
      $("#id_kezdes").datetimepicker({
        format: 'Y-m-d H:i',
        
      });
      $("#id_befejezes").datetimepicker({
        format: 'Y-m-d H:i',
        
      });
    });
  </script>

{% endblock javascripts %}